rescue => err
  puts "Error in #{__method__} in #{__FILE__}
  puts  "     #{err.inspect}"
  if err.respond_to?(:backtrace)
    context = err.backtrace.map {|x| "     " + x}.join("\n")
    puts context
  end
  abort "\nTerminated."
